### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by Nyette** [DiversityCorp/companies-on-blm#100]
## Feature description

The footer does not "stick" to the bottom of the browser window as it should. This is particularly noticeable whenever company data is lacking. I've provided a pic of the Riot Games profile as an example below.

## Benefits

It would improve user experience.

## Links / references

[Riot Games profile](https://imgur.com/a/crEhoE6)

**Comment by kelseyhuse30** [comment]
Thanks for reporting this, @Nyette ! I'm not sure why but the image is not appearing for me :(

**Comment by Nyette** [comment]
I edited my original comment. You should be able to view the pic now. May I work on this issue? I need practice with CSS.

**Comment by kelseyhuse30** [comment]
@Nyette you got it! Thanks for fixing the image, I can see it now and it def needs some work.
