### ISSUE TITLE
Set up pre-commit hook for markdown linter

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#110]
## Feature description

We've had some PR merges that failed build due to Markdown formatting issues.  

I'm not sure how to set up a precommit hook, but if we could use a `markdownlint` one, that would be helpful for preventing errors.

**Comment by Nyette** [comment]
I found this repo, [awesome-git-hooks](https://github.com/aitemr/awesome-git-hooks), earlier and it looked promising.

**Comment by kelseyhuse30** [comment]
Thank you, @Nyette !  The README has several links to documentation on how to set up pre-commit hooks as well, which looks very helpful.

**Comment by Nyette** [comment]
May I help you with this, @kelseyhuse30 ? I want to learn how to set up my own git hooks.

**Comment by kelseyhuse30** [comment]
@Nyette for sure!  if you get stuck, tag me in this ticket and I can take a look but otherwise i'll leave it up to you for now.
