### ISSUE TITLE
Statements date off by one day

### ISSUE THREAD

**Issue by hilbug** [DiversityCorp/companies-on-blm#114]
#### Issue description
During testing for a recent issue, I noticed the statement date in the date button for companies was off by one date. I noticed this on two companies: CVS and Cigna. Cigna's statement date was July 17 and CVS's statement date was Jun 12 but the statements page shows July 16 and June 11 respectively.

Found this in the 11ty docs: https://www.11ty.dev/docs/dates/#dates-off-by-one-day

#### Steps to reproduce the issue

1. Go to Statements page.
2. Click on Healthcare tag.
3. Review dates under CVS Health and Cigna.
4. Go to companies md file and compare the URL date to the statements page date.

## Platform details

Where is this occurring and more details about the environment (computer setup) of the customer.

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] Chrome

**Mobile (please complete the following information):** 
N/A

#### What's the expected result?

- The statements page date matches the URL date in the companies md document.

#### What's the actual result?

- The statements page date is off by one day.

#### Additional details / screenshot

- ![Screen Shot 2020-10-25 at 11 39 51 AM](https://user-images.githubusercontent.com/65197724/97111711-cd59b780-16b6-11eb-8427-a7f9129fb3df.png)
- ![Screen Shot 2020-10-25 at 11 42 38 AM](https://user-images.githubusercontent.com/65197724/97111812-317c7b80-16b7-11eb-9f59-1416d8b60424.png)

**Comment by kelseyhuse30** [comment]
Ack, thanks for reporting this @hilbug !  The screenshots are especially helpful.

**Comment by Nyette** [comment]
May I handle this issue?

**Comment by kelseyhuse30** [comment]
you got it @Nyette
