### ISSUE TITLE
Design cards for statements page

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#13]
## Feature description
On the homepage, each company has high-level info in a card view.
What all do we want to showcase in the card?  People can click on a card to go to a "Company" page which will have more information.

![image](https://user-images.githubusercontent.com/21069635/95667872-953c6b80-0b31-11eb-92f8-c20745db91fb.png)

**Comment by ravenclaw1999** [comment]
Maybe we have a picture of the statement or the general company logo if they don't have one, and add links to things like the D&I report
