### ISSUE TITLE
Failed build - postinstall script

### ISSUE THREAD

**Issue by Nyette** [DiversityCorp/companies-on-blm#133]
I believe the husky docs address this scenario. We may have to [disable hooks in CI](https://typicode.github.io/husky/#/?id=disable-hooks-in-ci), but I'm not sure.

**Comment by kelseyhuse30** [comment]
Thanks for identifying this one @Nyette  , I was able to fix the postinstall part but had some problems with the yaml linter precommit hook so commented it out for now 🤦🏻‍♀️

**Comment by Nyette** [comment]
There's a big chance we might not even need the `postinstall` script because there's a section that tells you how to [disable auto-install](https://github.com/typicode/husky/tree/master#disable-auto-install), which would suggest that auto-installing is default behavior. Husky also won't install on CI servers. I'm sorry about causing the failed build.

**Comment by kelseyhuse30** [comment]
> There's a big chance we might not even need the `postinstall` script because there's a section that tells you how to [disable auto-install](https://github.com/typicode/husky/tree/master#disable-auto-install), which would suggest that auto-installing is default behavior. Husky also won't install on CI servers. I'm sorry about causing the failed build.

Ooooh that is good to know. Thank you!  No reason to apologize - we're both learning 😂
