### ISSUE TITLE
Figure out what to do about linting

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#147]
## Feature description

We added a pre-commit hook but were having some small issues.  I need to do some more testing and researching.  When ready, revert commit ID d4ce4ab89c95ef66f04f74b497feb9e429a9b19e

**Comment by Nyette** [comment]
Let me know, if you need an extra pair of eyes/hands for this!

**Comment by kelseyhuse30** [comment]
@Nyette Yes! I am trying to remember all that we've gone through with this and what our problems were lol. If you have any notes, that would be a great start.

**Comment by Nyette** [comment]
I believe the problem we encountered emerged because of the `postinstall` script. When I was looking at the build for commit `5270261`, I saw this section:

```
husky > Setting up git hooks
CI detected, skipping Git hooks installation.
husky > Done
```

That was before we added the `is-ci` package, so husky can detect a CI server on its own and, by default, skip installation. We could remove the `is-ci` package and `postinstall` script because they might just be superfluous at this point. What do you think?

**Comment by kelseyhuse30** [comment]
@Nyette yeah that makes sense, I took them out for now so maybe we can leave it that way.  I'm also seeing that some people aren't running the server locally to test their code, so they don't install the dependencies that run the linter in the pre-commit hook.  That's ok, but then their formatting isn't fixed when they open the PR. :/

I'm wondering if we could look into some kind of bot that reviews PRs when they are opened and adds comments on lines that are formatted incorrectly?  We currently use "Stickler" at my job right now which shows errors for Python & Javascript.  And I've previously used Rubocop for Ruby.  So maybe there is a YAML one 🤔   That would help catch errors for people who aren't running it locally, and prevent me from having to call out formatting issues.

**Comment by Nyette** [comment]
That sounds like a great idea!

**Comment by Nyette** [comment]
[action-yamllint](https://github.com/reviewdog/action-yamllint) might be what we're looking for! What do you think? @kelseyhuse30

**Comment by kelseyhuse30** [comment]
> action-yamllint

omg YES! That's exactly what I was looking for.  And it has the code for using Github actions.  Do you wanna try it out?  I think you could add it to `.github/workflows`.

**Comment by Nyette** [comment]
Yeah, I'll give it a shot. I'll let you know, if I need help
