### ISSUE TITLE
Add additional resources to resources page

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#162]
#### Description

These article looks relevant to our cause. Let's add it to the /resources page!

- https://www.businessinsider.com/netflix-verna-myers-inclusion-how-to-lead-dei-initiatives-training-2020-10
- http://www.blackgirldangerous.com/2013/09/no-more-allies/

**Comment by dticed** [comment]
Articles added :)

**Comment by kelseyhuse30** [comment]
> Articles added :)

you're speedy! Did you want to take this one or are you opening a PR now, @dticed ?

**Comment by dticed** [comment]
> 
> 
> > Articles added :)
> 
> you're speedy! Did you want to take this one or are you opening a PR now, @dticed ?

I have already sent it
