### ISSUE TITLE
✏️  Homepage section about the corporate statements

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#164]
## Feature description

Move the meme from https://diversitycorp.co/statements/ to the homepage and make it smaller.  Write some content that demonstrates we are collecting these to highlight how widespread & predictable these statements were.

Something like "Corporate America had largely ignored the issue of police brutality, but for some reason after the murder of George Floyd, thousands of black & white statements flooded social media claiming that they are listening and will no longer be complicit." 

This can go to 1 person, or can be split up into 2 parts for design & content.

**Comment by bethqiang** [comment]
Hi! Would love to work on this. Can do both design & content. Let me know! 😃

**Comment by kelseyhuse30** [comment]
@bethqiang awesome!! That would be a ton of help.  I'm thinking before the timeline, but feel free to put it wherever you think makes the most sense.  We are excited to have you on the project!
