### ISSUE TITLE
🎨 Make the statements page a grid of the different images

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#165]
## Feature description

We have several images now collected of the statements.  Rather than listing the companies out in rows, we can probably do something interesting with the statement images.

Current state: https://diversitycorp.co/statements/

**Comment by Nyette** [comment]
May I work on this task?

**Comment by kelseyhuse30** [comment]
> May I work on this task?

@Nyette  Definitely!  I know that a few others were interested in design and were going to use Figma (I'm not familiar with that tool personally).  Feel free to experiment and do whatever you want though!  If you want any feedback as you go, please bring it up in the Slack channel 👍🏻 I am excited about this one!

**Comment by kelseyhuse30** [comment]
We implemented this a month ago
