### ISSUE TITLE
Add contributor guide

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#2]

**Comment by LaChapeliere** [comment]
Do you have specific wants or needs for this? Or do you want something very generic?

**Comment by LaChapeliere** [comment]
I'll make a PR then if that's okay

**Comment by ravenclaw1999** [comment]
Sounds good

**Comment by LaChapeliere** [comment]
@ravenclaw1999 You might want to close this if you're happy with my PR. Else I can add/change stuff, of course

**Comment by ravenclaw1999** [comment]
Hi, thanks for reminding me to close the issue and for contributing :)
