### ISSUE TITLE
Create page for Amazon

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#23]
## Feature description

Add in `companies` folder using similar formatting to `walmart.md`

**Comment by dialectrical** [comment]
I may be able to do this--to clarify, this would basically be copying the layout of walmart.md and collecting/inputing data relevant to Amazon?

**Comment by kelseyhuse30** [comment]
@dialectrical yep that's exactly it!  So you would create a new file in `companies` called `amazon.md` and fill out the info.  Feel free to add any extra fields if you find interesting info.

**Comment by kelseyhuse30** [comment]
@dialectrical i just realized we had someone else collect the data for Amazon.  Feel free to take any of the other companies!
