### ISSUE TITLE
Include this link for Pinterest

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#235]
Include this link in Pinterest's additional links

https://www.npr.org/2020/06/23/881624553/pinterest-sounds-a-more-contrite-tone-after-black-former-employees-speak-out

**Comment by arhamathar** [comment]
Assign this to me

**Comment by aditya28sarin** [comment]
Can you assign this issue to me.

**Comment by kelseyhuse30** [comment]
@aditya28sarin It looks like @arhamathar already opened a PR for this issue before I could assign it.  We would love to have you work on any of our other open issues, thank you so much for your interest! 💜
