### ISSUE TITLE
Include additional links for Google

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#237]
https://www.platformer.news/p/the-withering-email-that-got-an-ethical

https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/

https://www.nbcnews.com/tech/tech-news/second-top-black-female-google-employee-says-she-was-ousted-n1252277

https://outline.com/8emaNG

**Comment by aditya28sarin** [comment]
Can you elaborate more on this issue, I would like to work on it

**Comment by kelseyhuse30** [comment]
> Can you elaborate more on this issue, I would like to work on it

@aditya28sarin sure! In the repo, there is an existing file for Google data (`companies/google.md`).  This task would include adding an `additional resources` key at the bottom of the file and including these 3 links with titles.  The `companies/pinterest.md` file is a good one to look at to see how the additional resources are added.

**Comment by kelseyhuse30** [comment]
@aditya28sarin should I assign to you?

**Comment by aditya28sarin** [comment]
yes

**Comment by aditya28sarin** [comment]
is there any specific format for the `display_name` ?

**Comment by kelseyhuse30** [comment]
@aditya28sarin The title of the article is fine.  If there are special characters such as `:` in the title, it's best to surround it in quotes.  btw I added one more article so there are 4 :)

**Comment by aditya28sarin** [comment]
I was asking that the `pinterest.md` had  a `display_name` with each `url` at the bottom, so what should be the `display_name` here?

**Comment by kelseyhuse30** [comment]
@aditya28sarin ah ok let me try to explain a different way.  There will be 4 additional resources included, so for the first one it would look like this:

```yaml
url: https://www.platformer.news/p/the-withering-email-that-got-an-ethical
display_name: The withering email that got an ethical AI researcher fired at Google
```

The `display_name` is copied from the title of that article.

**Comment by aditya28sarin** [comment]
Sure! got it.

**Comment by aditya28sarin** [comment]
I have created a pull request ma'am, you can merge it if there are no further changes.
