### ISSUE TITLE
Create page for Costco Wholesale

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#24]
## Feature description

Add in `companies` folder using similar formatting to `walmart.md`

**Comment by Nimanita** [comment]
We have to create a page with the details in walmart.md file.Am I correct?if yes than please assign this issue to me

**Comment by kelseyhuse30** [comment]
@Nimanita assigned! You will create a new file in the `companies` folder called `costco.md` and use a similar format to the Walmart file - collect the name, forbes rank, URL for exec team, etc.

**Comment by Nimanita** [comment]
@kelseyhuse30 please add 

`hactoberfest-accepted`

 label in my pull request, if it having no problem.It will get counted for t-shirt. the link for hacktoberfest: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by kelseyhuse30** [comment]
Completed in PR #30
