### ISSUE TITLE
Add summaries for resources

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#241]
#### Issue Description
Currently there are no summaries for the resources on the resources page. If anyone wants to either add a short description to the resources already on the page or provide additional resources to add, that would be awesome :)

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by ravenclaw1999** [comment]
It's all yours!

**Comment by aditya28sarin** [comment]
I have added all the summaries on the resources page. Kindly let me know if I have added as it was intended to.
It is a great project to work on!

**Comment by ravenclaw1999** [comment]
Thank you so much! I will look over your PR :)
