### ISSUE TITLE
Include additional_resources for Salesforce

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#262]
Add these articles to the additional_resources field for Salesforce:

https://www.protocol.com/enterprise/salesforces-benioff-diversity-inclusion-woes
https://www.salesforce.com/news/stories/the-role-of-philanthropy-in-advancing-racial-equality-and-justice-in-2021/

**Comment by Nyette** [comment]
I'll work on this task!
