### ISSUE TITLE
Build a homepage

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#3]

**Comment by tanmayhinge** [comment]
i can build this up...looking at the current state it is not responsive and quite textbook ... i can work on it

**Comment by ravenclaw1999** [comment]
Sounds good, we were thinking of using the 11ty framework

**Comment by kelseyhuse30** [comment]
Hi @tanmayhinge ! Thank you so much for your interest in our project.  I've set up the 11ty framework in the project.  The homepage lives in the `index.njk` file.  Any of the [Bootstrap 4](https://getbootstrap.com/docs/4.0/getting-started/introduction/) classes are available for styling.  You can also join us on [Slack](https://join.slack.com/t/diversitycorpgroup/shared_invite/zt-hxc6fcol-Y_RQeN4sYrutcwX8gks8bQ) and we are happy to answer any questions :)
