### ISSUE TITLE
Add data for Cigna (Fortune13)

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#34]
## Feature description
Add a file with data for [Cigna](https://fortune.com/company/cigna/fortune500/)

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company.  If information for a field cannot be found, leave it blank or delete that line.

**Comment by hilbug** [comment]
@kelseyhuse30  I can take a few more. Feel free to assign to me. :)
