### ISSUE TITLE
Add data for Google (Fortune11)

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#36]
## Feature description
Add a file with data for [Google](https://fortune.com/company/alphabet/fortune500/).  Alphabet owns Google, so they are on the Fortune 500 as Alphabet but we should display Google.

https://about.google/commitments/racialequity/
https://blog.google/inside-google/company-announcements/standing-with-black-community

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company.  If information for a field cannot be found, leave it blank or delete that line.

**Comment by Reisclef** [comment]
I'll pick this one up if that's okay! :)

**Comment by kelseyhuse30** [comment]
@Reisclef thank you!! I'm going to update this one so it's for Google rather than Alphabet, but same thing.

**Comment by Reisclef** [comment]
Okay! That's done. I've stated Google everywhere as requested (makes sense as the urls are all google too). I added some bold to differentiate the two statements. Let me know if it needs further tidying.
