### ISSUE TITLE
Add data for Walgreens (Fortune19)

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#38]
#### Description

Add a file with data for [Walgreens Boot Alliance](https://fortune.com/company/walgreens-boots-alliance/fortune500/)

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

#### Helpful tips

Image: Save the image from a tweet, instagram, or Facebook post and rename it to the company name and place in the `images` folder. Reference the name of the file in the `image` field for the company you're working on.

Fortune Rank: Search for the company [here](https://fortune.com/fortune500/2020/search/). If they aren't ranked by Fortune, take this field out.

Twitter: Use the [advanced search](https://www.twitter.com/search-advanced) feature.
First, find the Twitter handle of the company (sometimes there are several) & CEO. Googling `twitter account <company name>` usually works.
Replace `zillow` in the following url with the name of the handle you are searching for.

https://twitter.com/search?q=(from%3Azillow)%20min_faves%3A10%20until%3A2020-06-05%20since%3A2020-05-28%20-filter%3Areplies

How this url works:

- `(from%3Azillow)%20`: from the @zillow account
- `min_faves%3A10%20`: minimum 10 likes
- `since%3A2020-05-28%20`: since May 28, 2020
- `until%3A2020-06-05%20`: until June 5, 2020
- `-filter%3Areplies`: filter replies

You can change these values in the URL to expand or narrow your search.

Google:

The following Google searches are helpful for finding statements & relevant articles about a company:

- <company name> Black Lives Matter
- <company name> George Floyd
- <company name> Diversity
- <company name> Inclusion

Instagram:

Google `<company name> Instagram` to find their account and scroll down towards the end of May/early June. The statement is generally a black background.

LinkedIn:

Google `<company name> LinkedIn` to find their account and locate a statement towards the end of May/early June.

**Comment by hilbug** [comment]
@kelseyhuse30  I can take this one.

**Comment by kelseyhuse30** [comment]
@hilbug Feel free to add this one as just "Walgreens" for the company name.

**Comment by hilbug** [comment]
Walgreens Links:
- CEO statement - May 31 2020 - https://www.walgreensbootsalliance.com/news-media/press-releases/2020/message-stefano-pessina-our-customers-team-members-and-communities
- An open letter on racial injustice - June 9 2020 - https://www.walgreensbootsalliance.com/news-media/our-stories/an-open-letter-on-racial-injustice
- Twitter - Pledge made on Juneteenth - June 19 2020 - https://twitter.com/walgreens/status/1273982657077141509?lang=en
- Cultural Diversity Q&A - May 21 2020 - https://www.walgreensbootsalliance.com/news-media/our-stories/when-were-different-it-pays-dividends
- Diversity and Inclusion - https://www.walgreensbootsalliance.com/corporate-responsibility/diversity-and-inclusion-report
- Healthy and Inclusive Workplace - https://www.walgreensbootsalliance.com/corporate-social-responsibility/healthy-and-inclusive-workplace
- Article - https://herald-review.com/business/mcdonald-s-walgreens-and-the-cubs-among-companies-condemning-racism-in-wake-of-george-floyd/article_57df576e-596e-5ca5-893c-0d57fcfb0600.html

**Comment by hilbug** [comment]
@kelseyhuse30 Working on these today- apologies for the lateness!
