### ISSUE TITLE
Set up a free postgresql database on Heroku

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#4]

**Comment by LaChapeliere** [comment]
Relational db scheme: https://dbdiagram.io/d/5f7f8afe3a78976d7b76ef2c

**Comment by LaChapeliere** [comment]
Corresponding .sql file
[DiversityCorp.zip](https://github.com/DiversityCorp/companies-on-blm/files/5357793/DiversityCorp.zip)

**Comment by EANimesha** [comment]
I can help in this issue. I have experience in heroku with postgres. Assign me and Send me more details. Do you have a app developed for this?

**Comment by kelseyhuse30** [comment]
@LaChapeliere @greendinosaur @EANimesha Thank you for your interest in our project!

We don't have anything setup on Heroku at the moment.  We now have our app setup to serve data that exists on the client side, so this task is not a high priority.  However, long-term we do want a database because we would like to use this data in other ways.  The design that @LaChapeliere put together is perfect and issue #9 has a CSV of data that we could upload.

Would you like to discuss more on our [Slack](https://join.slack.com/t/diversitycorpgroup/shared_invite/zt-hxc6fcol-Y_RQeN4sYrutcwX8gks8bQ) ?

**Comment by greendinosaur** [comment]
One deliverable could be too provide a script / documentation that creates the database and loads the data. That way, you can repeat the steps when you're ready to use a server side database with your app.

As @EANimesha has some experience, maybe @EANimesha produces this deliverable and I could test it out as I'm a newbie to heroku.

**Comment by LaChapeliere** [comment]
@greendinosaur @EANimesha I'm working on the queries to be able to fill the db from partial csv files, so the data collection can be crowd-sourced. I should have them done tomorrow or Tuesday.
For info, here's the fiddle I'm working on: https://dbfiddle.uk/?rdbms=postgres_12&fiddle=de4232f399d4b56496adf0f8e27790a6
Also, I've noticed that the scheme I shared uses features that are not compatible with all Postgres versions, so you might have to change minor elements. Don't hesitate to update us here in that case!

**Comment by greendinosaur** [comment]
Hi @LaChapeliere I've created a postgres database and created the supplied scheme. There were some issues and I had to change the .sql script.

1. `Year` is not a valid data type. I changed this to `date`. Or would you prefer this to be an Integer so you can store 2020 as the year?
2. `tinyint` is not a valid data type. I changed this to `smallint`
3. I also had to change `datetime` to `timestamp`

Then the script worked 😃 Let me know what you'd like to do about Year. Then I can update the script and create a PR so you can store it in the repo. I can also provide the commands to create the database in Heroku and to import the schema.

The short answer to create the database was to use the Heroku CLI. I then installed the pgsql CLI tool onto my local machine, connected to the new database and imported the file. Something along the lines of:

After registering for an Heroku account, installing the Heroku CLI and creating a simple app
- `heroku addons:create heroku-postgresql:hobby-dev -a <NAME OF APP>`

Installing the pgsql CLI
I use a Mac so used Homebrew to install the pgsql CLI
- `brew install libpq`
- `brew link --force libpq`
- `echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.zshrc`

To create the database tables
- `psql <very long database connection string>`
- `\i diversitycorp.sql`
- `\dt`

**Comment by LaChapeliere** [comment]
@greendinosaur Great! I think Year would work better as a smallint, thanks.
Once the heroku database is up, it can be population by using the heroku cli, right?
I have the basics of the queries ready to populate from partial csv files, but the "uploading" is the part I haven't quite figured out yet.

**Comment by greendinosaur** [comment]
As far as I can tell, there are two options for uploading.

- Either write a script in a language of your choice that reads the file and inserts into the database or

- use the pgsql command line tool as that has the ability to import from CSV.

I will make the changes to the create database SQL file and send that through via a PR.

I think that once you have an app on Heroku, I can transfer ownership of the database I've created to your app.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
