### ISSUE TITLE
Instructions on how to submit data for website visitors

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#46]
## Feature description

Add instructions on the site on how to submit data.

1. Link to Github where people can open pull request
2. For people who are not Github users, should we have a Google form where they can submit info anonymously? Or email us?

**Comment by kelseyhuse30** [comment]
Created a google form here: https://forms.gle/NCgQ1G1p1BxJVcgd7

**Comment by ravenclaw1999** [comment]
I can add a "Contribute" page to the site
