### ISSUE TITLE
Add javascript function to sort by BLM posted date

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#48]
## Feature description

We would like to be able to list companies in order of when they posted their BLM statement.  I think we can add a sort function to `.eleventy.js` to accomplish this for us.

For now, use it for the 'statements' page to sort from oldest to newest.

**Comment by Nyette** [comment]
May I work on this?

**Comment by kelseyhuse30** [comment]
> May I work on this?

Yep you got it! Let me know if you need any guidance, I think I have seen some instructions in the 11ty documentation on how to sort a collection. Assigning to you 🌟
