### ISSUE TITLE
Set up 11ty framework

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#5]
I haven't finalized the language I will be using, but it will likely be a react app, so that people can easily contribute, and add more statements for more companies.

**Comment by Jethet** [comment]
Hello @ravenclaw1999 , your mission is great and I would like to contribute. I am not an experienced developer but have done some React projects (also quite basic).
What is the issue: you need the React folder set-up created for the frontend? Any details?

**Comment by ravenclaw1999** [comment]
Hi, thanks for reaching out. We were thinking of using the 11ty framework. It would be great if you could work on setting this up! Here's a link to some of 11ty's tutorials: https://www.11ty.dev/docs/tutorials/.

**Comment by Jethet** [comment]
OK, I'll have a look. Never heard of it, tbh. I'll let you know if I think I can do something useful for the project, first dig into this.

**Comment by Jethet** [comment]
@ravenclaw1999  I have checked out 11ty but I think I would need some time to get to grips with it, and then I probably would not be able to help beyond the basics. There is a lot I am still learning, and I think adding 11ty to this is a bit much. I am learning React, and I thought you were going to start a React app. This one is not for me I think.

**Comment by ravenclaw1999** [comment]
That's totally fine, don't worry about it. We will be adding more issues, so look out for those :)
