### ISSUE TITLE
Add data for USA Softball

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#50]
#### Description

Add a file with data for USA Softball.
Here's their tweet: https://twitter.com/USASoftball/status/1267911166271066116?s=20
They aren't on the the Fortune list, so can leave that data out.

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Reisclef** [comment]
I'll have a go at this, and if it goes well, I might look into more. What an interesting idea!

**Comment by kelseyhuse30** [comment]
Thanks @Reisclef ! Let us know if you have any questions, we are happy to help. I've assigned this one to you. :)
