### ISSUE TITLE
Include the 'statement from [Brand]' meme somewhere in the site

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#52]
## Feature description

from [this tweet](https://twitter.com/Campster/status/1267183124582215680?s=20)
![image](https://user-images.githubusercontent.com/21069635/96385383-18287c00-1159-11eb-900c-67d713721a50.png)

**Comment by ravenclaw1999** [comment]
For now, I added it to the statements page, but I will probably play around with where to place it and its styling
