### ISSUE TITLE
Add data for Redfin

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#53]
#### Description

Add a file with data for Redfin.  They may not be on the Fortune 500.

Here are 2 of their statements:
https://twitter.com/Redfin/status/1271141352927969281?s=20
https://twitter.com/Redfin/status/1267211947973283840?s=20

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Nyette** [comment]
Is this task still available? I would like to work on it.

**Comment by kelseyhuse30** [comment]
@Nyette yes, assigned it to you! Thank you for offering to help :)
