### ISSUE TITLE
Add data for Zillow

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#54]
#### Description

Add a file with data for Zillow. They may not be in the Fortune500.

Here are some of their posts:
https://twitter.com/zillow/status/1266893361358626816?s=20
https://twitter.com/zillow/status/1271144265440096262?s=20
https://twitter.com/Rich_Barton/status/1270345611586330625?s=20

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by hilbug** [comment]
@kelseyhuse30 I'd like to help with this project. Can I work on this one? Thanks! ~Hilary

**Comment by kelseyhuse30** [comment]
@hilbug assigned to you, thank you for helping us!

**Comment by hilbug** [comment]
Created pull request #61 for this issue.
