### ISSUE TITLE
Add data for Marvel Studios

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#65]
#### Description

Add a file with data for Marvel Studios

https://twitter.com/EAMaddenNFL/status/1267172458290974720?s=20

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Nyette** [comment]
I'd like to work on this task!

**Comment by Nyette** [comment]
> Marvel Studios, LLC is an American film and television studio that is a subsidiary of The Walt Disney Studios

Should I just list Walt Disney's Fortune 500 rank? Many of their links lead back to the Walt Disney site.

**Comment by kelseyhuse30** [comment]
> > Marvel Studios, LLC is an American film and television studio that is a subsidiary of The Walt Disney Studios
> 
> Should I just list Walt Disney's Fortune 500 rank? Many of their links lead back to the Walt Disney site.

That sounds good to me!
