### ISSUE TITLE
Add data for Playstation

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#68]
#### Description

Add a file with data for Playstation (owned by Sony)

https://twitter.com/PlayStation/status/1267468949865639936?s=20

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Nyette** [comment]
I'd like to work on this task!
