### ISSUE TITLE
Add data for Arc'teryx

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#73]
#### Description

Add a file with data for Arc'teryx

https://www.instagram.com/p/CA5v5wYJsb0/

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by erin-sparkbox** [comment]
I can take this one!

**Comment by kelseyhuse30** [comment]
Awesome, thank you @erin-sparkbox and welcome to the project!
