### ISSUE TITLE
Add data for Brown Girls Climb

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#75]
#### Description

Add a file with data for Brown Girls Climb

https://www.facebook.com/Backcountry/photos/a.27590299986/10151481897144987/

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Nyette** [comment]
I'd like to work on this issue
