### ISSUE TITLE
Add data for Atlassian

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#78]
#### Description

Add a file with data for Atlassian

https://www.atlassian.com/blog/announcements/the-standard-you-walk-past-is-the-standard-you-accept

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Nyette** [comment]
May I work on this issue?
