### ISSUE TITLE
Add data for Github

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#79]
#### Description

Add a file with data for Github

https://twitter.com/natfriedman/status/1266790816174882816?s=20

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by ihristova11** [comment]
@kelseyhuse30 Would like to work on this. :)
