### ISSUE TITLE
Add data for Intel

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#84]
#### Description

Add a file with data for Intel

https://newsroom.intel.com/news/bob-swan-note-to-intel-employees/

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by StephaneRocha** [comment]
Hi, I'll be working on this

**Comment by kelseyhuse30** [comment]
Welcome to the project @StephaneRocha ! We're glad you found us :)

**Comment by StephaneRocha** [comment]
Thank you! :heart:
