### ISSUE TITLE
Add data for Slack

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#86]
#### Description

Add a file with data for Slack

https://twitter.com/SlackHQ/status/1267825650397671424
https://twitter.com/SlackHQ/status/1267825653769842690
https://slackhq.com/diversity-at-slack-2020
https://slackhq.com/statement-from-slack-condemning-white-supremacy-and-violence-against-the-black-community

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by EmilyMatt** [comment]
I can do that, for sure^
