### ISSUE TITLE
Add data for Salesforce

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#87]
#### Description

Add a file with data for Salesforce

https://twitter.com/salesforce/status/1266066647275757568
https://equalitydata.herokuapp.com/
https://www.salesforce.com/video/11052929/

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by Bellex0** [comment]
@kelseyhuse30  fixed issue
