### ISSUE TITLE
Add data for Zoom

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#88]
#### Description

Add a file with data for Zoom

https://twitter.com/zoom_us/status/1266877451646283776

Use `companies-on-blm/examples/add-a-company.md` as a reference for how to add data for a company. If information for a field cannot be found, leave it blank or delete that line.

**Comment by thisLinda** [comment]
Hello, may I be assigned to this please?

**Comment by kelseyhuse30** [comment]
@thisLinda you got it! Welcome to our project :D 💓

**Comment by thisLinda** [comment]
Thank you @kelseyhuse30! I got carried away and did a second issue and hopefully did not create a mess with the pull request. I tried to separate them into two but that didn't work so for the sake of not making a potentially worse mess I've left it the way it is. I have no doubt you will inform me of any steps I need to take to fix. 

Thank you for the opportunity to work on the project. I will continue to follow this repo and offer assistance as my skills improve.

**Comment by kelseyhuse30** [comment]
Thank you @thisLinda ! Not a problem that they are combined together :)

**Comment by kelseyhuse30** [comment]
@thisLinda I'll be working on the app tomorrow from 2-3:30 Central time if you want any help sorting out the PR due to git wonkiness!  Feel free to coordinate with us on our Slack, here is an invite link: https://join.slack.com/t/diversitycorpgroup/shared_invite/zt-hxc6fcol-Y_RQeN4sYrutcwX8gks8bQ
