### ISSUE TITLE
Failed build - YAML error

### ISSUE THREAD

**Issue by kelseyhuse30** [DiversityCorp/companies-on-blm#97]
@Bellex0  I think the new Salesforce data file had a problem :( Would you mind correcting the date in the file that had just `2020`? You can make up a date, today's date is fine.

![image](https://user-images.githubusercontent.com/21069635/96771662-95e1c700-13a7-11eb-82d7-aa469cbda8ca.png)

**Comment by Nyette** [comment]
I'll fix this!

**Comment by Bellex0** [comment]
@kelseyhuse30 Yes! I fixed the issue by putting in today's date.
